/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemagestioninventario;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JTextField;

/**
 *
 * @author Ancor
 */
public class AddProduct extends javax.swing.JFrame {

    /**
     * Creates new form CreateProduct
     */
    private int newId;
    private boolean operationType;
    private View v;
    private int tableObjectId;
    private Product editProduct;
    
    public AddProduct(Boolean addOperation, View v) {
        
        initComponents();
        this.setVisible(true);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setResizable(false);

        jLabel1.setText(" ");       
        jLabel2.setText(" ");
        jLabel3.setText(" ");
        jLabel4.setText(" ");
            
        newId = v.productList.getProducts().size();
        this.v = v;
        this.operationType = addOperation;
        if (!operationType) {
            this.tableObjectId = v.getjTable2().getSelectedRow();
            System.out.println(v.productList.getProductAt(tableObjectId).getId());
            NameField.setText(v.getjTable2().getValueAt(tableObjectId, 0).toString());
            QuantityField.setText(v.getjTable2().getValueAt(tableObjectId, 1).toString());
            PriceField.setText(v.getjTable2().getValueAt(tableObjectId, 2).toString());
            CategoryField.setText(v.getjTable2().getValueAt(tableObjectId, 3).toString().toString());
        }
        
        addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e) {
                v.setEnabled(true);
            }
        });
    };
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileName1 = new javax.swing.JLabel();
        QuantityField = new javax.swing.JTextField();
        FileName2 = new javax.swing.JLabel();
        PriceField = new javax.swing.JTextField();
        FileName3 = new javax.swing.JLabel();
        CategoryField = new javax.swing.JTextField();
        FileName4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        NameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FileName1.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        FileName1.setText("Quantity");

        QuantityField.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        QuantityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityFieldActionPerformed(evt);
            }
        });

        FileName2.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        FileName2.setText("Price");

        PriceField.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        PriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceFieldActionPerformed(evt);
            }
        });

        FileName3.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        FileName3.setText("Category");

        CategoryField.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        CategoryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryFieldActionPerformed(evt);
            }
        });

        FileName4.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        FileName4.setText("€");

        jButton1.setForeground(new java.awt.Color(0, 204, 0));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        NameField.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("jLabel1");

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("jLabel1");

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FileName3)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addComponent(CategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FileName1)
                            .addComponent(FileName2))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FileName4))
                            .addComponent(QuantityField, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FileName1)
                    .addComponent(QuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FileName2)
                    .addComponent(PriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FileName4))
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FileName3)
                    .addComponent(CategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int cantidad;
        int isValid = 0;
        
        // NAME FIELD
        
        if (!"".equals(NameField.getText())) {
            if (NameField.getText().length() <= 25) {
                jLabel4.setText(" ");
                isValid++;
            } else {
                jLabel4.setText("^ Name too long (25)");
            }
        } else {
            jLabel4.setText("^ This field must be filled");
        }
        
        //QUANTITY FIELD
        
        if (!"".equals(QuantityField.getText())){
            if (QuantityField.getText().matches("\\d+")){
                jLabel1.setText(" ");
                isValid++;
            } else {
                jLabel1.setText("^ Must be a whole number between 1 - 9999");
            }
        } else {
            jLabel1.setText("^ This field must be filled");
        }
        
        // PRICE FIELD
        
        if (!"".equals(PriceField.getText())) {
            if (PriceField.getText().matches("\\d+(\\.,\\d+)?")) {
                jLabel2.setText(" ");
                isValid++;
            } else {
                jLabel2.setText("^ Must be a decimal(.) number between 1 - 9999");
            }
        } else {
            jLabel2.setText("^ This field must be filled");
        }
        
        // CATEGORY FIELD
        
        if (!"".equals(CategoryField.getText())) {
            if (CategoryField.getText().length() <= 25) {
                jLabel3.setText(" ");
                isValid++;
            } else {
                jLabel3.setText("^ Category too long (25)");
            }
        } else {
            jLabel3.setText("^ This field must be filled");
        }

        if (isValid == 4) {
            if (operationType) {
                Product product = new Product(newId, NameField.getText(),
                        Integer.parseInt(QuantityField.getText()),
                        Float.parseFloat(PriceField.getText()),
                        CategoryField.getText());
                v.AddProduct(product);
                this.dispose();
            } else if (!operationType) {
                editProduct = new Product(v.productList.getProductAt(tableObjectId).getId(), NameField.getText(), Integer.parseInt(QuantityField.getText()), Float.parseFloat(PriceField.getText()), CategoryField.getText());
                v.UpdateProduct(editProduct, tableObjectId);
                this.dispose();
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        v.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        
    }//GEN-LAST:event_NameFieldActionPerformed

    private void QuantityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityFieldActionPerformed

    private void PriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceFieldActionPerformed

    private void CategoryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoryFieldActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CategoryField;
    private javax.swing.JLabel FileName1;
    private javax.swing.JLabel FileName2;
    private javax.swing.JLabel FileName3;
    private javax.swing.JLabel FileName4;
    private javax.swing.JTextField NameField;
    private javax.swing.JTextField PriceField;
    private javax.swing.JTextField QuantityField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
